/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_suyux_opencv_face_detection_new_NativeClass */

#ifndef _Included_com_example_suyux_opencv_face_detection_new_NativeClass
#define _Included_com_example_suyux_opencv_face_detection_new_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_suyux_opencv_face_detection_new_NativeClass
 * Method:    getMessageFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_suyux_opencv_1face_1detection_1new_NativeClass_getMessageFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
