/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>

/* Header for class com_example_suyux_opencv_face_detection_4_OpencvClass */

#ifndef _Included_com_example_suyux_opencv_face_detection_4_OpencvClass
#define _Included_com_example_suyux_opencv_face_detection_4_OpencvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_suyux_opencv_face_detection_4_OpencvClass
 * Method:    faceDetection
 * Signature: (J)V
 */
void detect(Mat& frame);

JNIEXPORT void JNICALL Java_com_example_suyux_opencv_1face_1detection_14_OpencvClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
